// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// CSVReader is an autogenerated mock type for the CSVReader type
type CSVReader struct {
	mock.Mock
}

// Read provides a mock function with given fields: fileName
func (_m *CSVReader) Read(fileName string) ([][]string, error) {
	ret := _m.Called(fileName)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 [][]string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([][]string, error)); ok {
		return rf(fileName)
	}
	if rf, ok := ret.Get(0).(func(string) [][]string); ok {
		r0 = rf(fileName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(fileName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCSVReader creates a new instance of CSVReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCSVReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *CSVReader {
	mock := &CSVReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
